# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./
    strategy:
      matrix:
        node-version: [12.16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
        working-directory: ${{ env.working-directory }}
      - run: npm run build --if-present
        working-directory: ${{ env.working-directory }}

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'cherrychart.client'
          AWS_ACCESS_KEY_ID: ${{ secrets. AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: '.next'
  refreshwork:
    runs-on: self-hosted
    needs: build
    env:
      client-directory: /home/ubuntu/CherryChart-Client

    strategy:
      matrix:
        node-version: [12.16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: pull source
        run: sudo git pull origin master
        working-directory: ${{ env.client-directory }}

      - name: install npm packages
        run: sudo npm i
        working-directory: ${{ env.client-directory }}

      - name: sync build directory to s3
        run: sudo npm run deploy
        working-directory: ${{ env.client-directory }}

      - name: reload
        run: sudo pm2 reload client
        working-directory: ${{ env.client-directory }}

      - name: pm2 list
        run: sudo pm2 list
        working-directory: ${{ env.client-directory }}
        
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() # Pick up events even if the job fails or is canceled.
